export const ants = [
  {
    id: "0",
    location: { x: -1, y: -1, z: 0 },
    taskCurrent: {
      id: "oUezYPzkmB9EUyV6UheZ",
      name: "Forage",
      description: "",
    },
    memory: [],
    food: null,
  },
  {
    id: "1",
    location: { x: -1, y: -1, z: 0 },
    taskCurrent: {
      id: "oUezYPzkmB9EUyV6UheZ",
      name: "Forage",
      description: "",
    },
    memory: [],
    food: null,
  },
  {
    id: "2",
    location: { x: -1, y: -1, z: 0 },
    taskCurrent: {
      id: "oUezYPzkmB9EUyV6UheZ",
      name: "Forage",
      description: "",
    },
    memory: [],
    food: null,
  },
  {
    id: "3",
    location: { x: -1, y: -1, z: 0 },
    taskCurrent: {
      id: "oUezYPzkmB9EUyV6UheZ",
      name: "Forage",
      description: "",
    },
    memory: [],
    food: null,
  },
  {
    id: "4",
    location: { x: -1, y: -1, z: 0 },
    taskCurrent: {
      id: "oUezYPzkmB9EUyV6UheZ",
      name: "Forage",
      description: "",
    },
    memory: [],
    food: null,
  },
  {
    id: "5",
    location: { x: -1, y: -1, z: 0 },
    taskCurrent: {
      id: "oUezYPzkmB9EUyV6UheZ",
      name: "Forage",
      description: "",
    },
    memory: [],
    food: null,
  },
  {
    id: "6",
    location: { x: -1, y: -1, z: 0 },
    taskCurrent: {
      id: "oUezYPzkmB9EUyV6UheZ",
      name: "Forage",
      description: "",
    },
    memory: [],
    food: null,
  },
  {
    id: "7",
    location: { x: -1, y: -1, z: 0 },
    taskCurrent: {
      id: "oUezYPzkmB9EUyV6UheZ",
      name: "Forage",
      description: "",
    },
    memory: [],
    food: null,
  },
  {
    id: "8",
    location: { x: -1, y: -1, z: 0 },
    taskCurrent: {
      id: "oUezYPzkmB9EUyV6UheZ",
      name: "Forage",
      description: "",
    },
    memory: [],
    food: null,
  },
  {
    id: "9",
    location: { x: -1, y: -1, z: 0 },
    taskCurrent: {
      id: "oUezYPzkmB9EUyV6UheZ",
      name: "Forage",
      description: "",
    },
    memory: [],
    food: null,
  },
  {
    id: "10",
    location: { x: -1, y: -1, z: 0 },
    taskCurrent: {
      id: "oUezYPzkmB9EUyV6UheZ",
      name: "Forage",
      description: "",
    },
    memory: [],
    food: null,
  },
  {
    id: "11",
    location: { x: -1, y: -1, z: 0 },
    taskCurrent: {
      id: "oUezYPzkmB9EUyV6UheZ",
      name: "Forage",
      description: "",
    },
    memory: [],
    food: null,
  },
  {
    id: "12",
    location: { x: -1, y: -1, z: 0 },
    taskCurrent: {
      id: "oUezYPzkmB9EUyV6UheZ",
      name: "Forage",
      description: "",
    },
    memory: [],
    food: null,
  },
  {
    id: "13",
    location: { x: -1, y: -1, z: 0 },
    taskCurrent: {
      id: "oUezYPzkmB9EUyV6UheZ",
      name: "Forage",
      description: "",
    },
    memory: [],
    food: null,
  },
  {
    id: "14",
    location: { x: -1, y: -1, z: 0 },
    taskCurrent: {
      id: "oUezYPzkmB9EUyV6UheZ",
      name: "Forage",
      description: "",
    },
    memory: [],
    food: null,
  },
  {
    id: "15",
    location: { x: -1, y: -1, z: 0 },
    taskCurrent: {
      id: "oUezYPzkmB9EUyV6UheZ",
      name: "Forage",
      description: "",
    },
    memory: [],
    food: null,
  },
  {
    id: "16",
    location: { x: -1, y: -1, z: 0 },
    taskCurrent: {
      id: "oUezYPzkmB9EUyV6UheZ",
      name: "Forage",
      description: "",
    },
    memory: [],
    food: null,
  },
  {
    id: "17",
    location: { x: -1, y: -1, z: 0 },
    taskCurrent: {
      id: "oUezYPzkmB9EUyV6UheZ",
      name: "Forage",
      description: "",
    },
    memory: [],
    food: null,
  },
  {
    id: "18",
    location: { x: -1, y: -1, z: 0 },
    taskCurrent: {
      id: "oUezYPzkmB9EUyV6UheZ",
      name: "Forage",
      description: "",
    },
    memory: [],
    food: null,
  },
  {
    id: "19",
    location: { x: -1, y: -1, z: 0 },
    taskCurrent: {
      id: "oUezYPzkmB9EUyV6UheZ",
      name: "Forage",
      description: "",
    },
    memory: [],
    food: null,
  },
  {
    id: "20",
    location: { x: -1, y: -1, z: 0 },
    taskCurrent: {
      id: "oUezYPzkmB9EUyV6UheZ",
      name: "Forage",
      description: "",
    },
    memory: [],
    food: null,
  },
];
